services:
    db:
        image: mariadb:latest
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
        volumes:
            - ./DB:/docker-entrypoint-initdb.d
            - persistente:/var/lib/mysql
        networks:
            - default
    phpmydb:
        image: mysql
        ports: 
            - "0.0.0.0:3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
        volumes:
            - ./DB:/docker-entrypoint-initdb.d
            - persistente:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - "0.0.0.0:8000:80"
        environment:
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
volumes:
    persistente: